// Code generated by internal/mihomo/cmd/genrules. DO NOT EDIT.

export interface MihomoRuleTypeGroup {
	label: string;
	items: string[];
}

export const MIHOMO_SUPPORTED_RULE_TYPES: MihomoRuleTypeGroup[] = [
	{
		label: "Домены",
		items: [
			"DOMAIN",
			"DOMAIN-SUFFIX",
			"DOMAIN-KEYWORD",
			"DOMAIN-WILDCARD",
			"DOMAIN-REGEX",
			"GEOSITE",
		]
	},
	{
		label: "IP и сети",
		items: [
			"IP-CIDR",
			"IP-CIDR6",
			"IP-SUFFIX",
			"IP-ASN",
			"GEOIP",
			"SRC-GEOIP",
			"SRC-IP-ASN",
			"SRC-IP-CIDR",
			"SRC-IP-SUFFIX",
		]
	},
	{
		label: "Порты и входы",
		items: [
			"DST-PORT",
			"SRC-PORT",
			"IN-PORT",
			"IN-TYPE",
			"IN-USER",
			"IN-NAME",
			"REMATCH-NAME",
			"NETWORK",
			"DSCP",
		]
	},
	{
		label: "Процесс",
		items: [
			"PROCESS-PATH",
			"PROCESS-PATH-WILDCARD",
			"PROCESS-PATH-REGEX",
			"PROCESS-NAME",
			"PROCESS-NAME-WILDCARD",
			"PROCESS-NAME-REGEX",
			"UID",
		]
	},
	{
		label: "Составные",
		items: [
			"RULE-SET",
			"AND",
			"OR",
			"NOT",
			"MATCH",
		]
	},
];

export const ALL_MIHOMO_RULE_TYPES: readonly string[] = [
	"AND",
	"DOMAIN",
	"DOMAIN-KEYWORD",
	"DOMAIN-REGEX",
	"DOMAIN-SUFFIX",
	"DOMAIN-WILDCARD",
	"DSCP",
	"DST-PORT",
	"GEOIP",
	"GEOSITE",
	"IN-NAME",
	"IN-PORT",
	"IN-TYPE",
	"IN-USER",
	"IP-ASN",
	"IP-CIDR",
	"IP-CIDR6",
	"IP-SUFFIX",
	"MATCH",
	"NETWORK",
	"NOT",
	"OR",
	"PROCESS-NAME",
	"PROCESS-NAME-REGEX",
	"PROCESS-NAME-WILDCARD",
	"PROCESS-PATH",
	"PROCESS-PATH-REGEX",
	"PROCESS-PATH-WILDCARD",
	"REMATCH-NAME",
	"RULE-SET",
	"SRC-GEOIP",
	"SRC-IP-ASN",
	"SRC-IP-CIDR",
	"SRC-IP-SUFFIX",
	"SRC-PORT",
	"UID",
] as const;

export type MihomoSupportedRuleType = (typeof ALL_MIHOMO_RULE_TYPES)[number];
