package mcp

import (
	"context"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

type setRuleOutboundIn struct {
	Index    int    `json:"index" jsonschema:"rule position from list_singbox_rules"`
	Outbound string `json:"outbound" jsonschema:"target outbound tag from list_singbox_outbounds or list_singbox_tunnels"`
}

type rulesOut struct {
	Rules []SingboxRule `json:"rules" jsonschema:"in evaluation order — sing-box takes the FIRST rule that matches"`
	// HasDraft repeats the staging flag here because these rules come from
	// the draft when one exists: an agent reading them as live would
	// report a change that nobody has applied.
	HasDraft bool `json:"hasDraft" jsonschema:"true means these rules include staged, NOT YET APPLIED edits"`
}

type outboundsOut struct {
	Outbounds []SingboxOutbound `json:"outbounds"`
}

type stagedOut struct {
	Staged bool `json:"staged" jsonschema:"always true: the change is in the draft and does NOT affect traffic until apply_singbox_staging"`
	Index  int  `json:"index"`
}

type applyOut struct {
	Applied bool `json:"applied"`
}

type discardOut struct {
	Discarded bool `json:"discarded"`
}

// stagedNotice is attached to every staging write so the model cannot
// report the change as live. Structured output alone is not enough: a
// model that skims tends to read "staged: true" as "done".
const stagedNotice = "The change is staged, not applied: traffic still follows the previous configuration. " +
	"Call apply_singbox_staging to publish it, or tell the user it is waiting in the web interface."

func registerRouterTools(s *mcp.Server, d Deps) {
	mcp.AddTool(s, &mcp.Tool{
		Name: "list_singbox_rules",
		Description: "Routing rules of the sing-box router, in evaluation order — sing-box uses the FIRST rule that matches, so position decides the outcome. " +
			"Rules marked managed are generated by awg-manager and rewritten on the next reconcile; editing one has no lasting effect. " +
			"These are separate from the NDMS domain lists in list_dns_routes.",
		Annotations: readOnly("List sing-box rules"),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, _ empty) (*mcp.CallToolResult, rulesOut, error) {
		rules, hasDraft, err := d.ListSingboxRules(ctx)
		if rules == nil {
			rules = []SingboxRule{}
		}
		return nil, rulesOut{Rules: rules, HasDraft: hasDraft}, err
	})

	mcp.AddTool(s, &mcp.Tool{
		Name: "list_singbox_outbounds",
		Description: "Composite routing targets defined in the sing-box router (selectors and urltest groups) that a rule can point at. " +
			"A rule may also target a single proxy from list_singbox_tunnels, or the built-in direct and block.",
		Annotations: readOnly("List sing-box outbounds"),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, _ empty) (*mcp.CallToolResult, outboundsOut, error) {
		list, err := d.ListSingboxOutbounds(ctx)
		if list == nil {
			list = []SingboxOutbound{}
		}
		return nil, outboundsOut{Outbounds: list}, err
	})

	mcp.AddTool(s, &mcp.Tool{
		Name: "get_singbox_staging",
		Description: "Whether the sing-box router has unapplied changes waiting, and when they were drafted. " +
			"A draft may hold edits made in the web interface as well as through MCP — they share one draft.",
		Annotations: readOnly("Sing-box staging status"),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, _ empty) (*mcp.CallToolResult, SingboxStaging, error) {
		out, err := d.SingboxStaging(ctx)
		return nil, out, err
	})

	mcp.AddTool(s, &mcp.Tool{
		Name: "set_singbox_rule_outbound",
		Description: "Send one routing rule's traffic through a different outbound. The edit goes into the router's DRAFT and changes nothing until apply_singbox_staging runs. " +
			"Rules generated by awg-manager cannot be edited this way.",
		Annotations: safeWrite("Set rule outbound", true),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, in setRuleOutboundIn) (*mcp.CallToolResult, stagedOut, error) {
		if in.Index < 0 {
			return nil, stagedOut{}, fmt.Errorf("index must not be negative (use list_singbox_rules)")
		}
		if strings.TrimSpace(in.Outbound) == "" {
			return nil, stagedOut{}, fmt.Errorf("outbound is required (use list_singbox_outbounds)")
		}
		if err := d.SetSingboxRuleOutbound(ctx, in.Index, strings.TrimSpace(in.Outbound)); err != nil {
			return nil, stagedOut{}, err
		}
		return &mcp.CallToolResult{Content: []mcp.Content{&mcp.TextContent{Text: stagedNotice}}},
			stagedOut{Staged: true, Index: in.Index}, nil
	})

	mcp.AddTool(s, &mcp.Tool{
		Name: "apply_singbox_staging",
		Description: "Publish the sing-box router's draft: validate it and reload the engine. " +
			"WARNING: this applies the WHOLE draft, including any edits the user started in the web interface and has not finished. " +
			"Check get_singbox_staging first and confirm with the user when the draft is not only yours.",
		Annotations: safeWrite("Apply sing-box draft", false),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, _ empty) (*mcp.CallToolResult, applyOut, error) {
		if err := d.ApplySingboxStaging(ctx); err != nil {
			return nil, applyOut{}, err
		}
		return nil, applyOut{Applied: true}, nil
	})

	mcp.AddTool(s, &mcp.Tool{
		Name: "discard_singbox_staging",
		Description: "Throw away the sing-box router's draft and return to the applied configuration. " +
			"DESTRUCTIVE: the draft is shared, so this also destroys unfinished edits the user made in the web interface, and they cannot be recovered. " +
			"Confirm with the user before calling it.",
		Annotations: destructiveWrite("Discard sing-box draft", true),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, _ empty) (*mcp.CallToolResult, discardOut, error) {
		if err := d.DiscardSingboxStaging(ctx); err != nil {
			return nil, discardOut{}, err
		}
		return nil, discardOut{Discarded: true}, nil
	})
}
