package mcp

import "time"

// Plain data types crossing the Deps boundary. JSON tags mirror the
// daemon's storage/service types so localdeps can convert by JSON
// round-trip; the fake and cmd/mcp-dev use them directly.

type WANInterface struct {
	Name     string `json:"name"`
	Up       bool   `json:"up"`
	Label    string `json:"label"`
	Priority int    `json:"priority"`
}

type SingboxStatus struct {
	Installed   bool   `json:"installed"`
	Running     bool   `json:"running"`
	Version     string `json:"version,omitempty"`
	TunnelCount int    `json:"tunnelCount"`
	LastError   string `json:"lastError,omitempty"`
}

// SingboxTunnel is one proxy configured inside sing-box. Credentials
// (passwords, uuids, the naive username) are deliberately left out: an
// agent needs to tell proxies apart and see whether they work, not to
// reproduce them. Use the web UI to read a proxy's secrets.
type SingboxTunnel struct {
	Tag      string `json:"tag" jsonschema:"unique name of the proxy; the id every other sing-box tool takes"`
	Protocol string `json:"protocol" jsonschema:"vless|hysteria2|naive"`
	Server   string `json:"server,omitempty"`
	Port     int    `json:"port,omitempty"`
	Security string `json:"security,omitempty" jsonschema:"reality|tls|none"`
	// Transport is the stream the protocol runs over: tcp|grpc|quic|https.
	Transport      string `json:"transport,omitempty"`
	ListenPort     int    `json:"listenPort,omitempty" jsonschema:"local SOCKS5 port this proxy listens on"`
	ProxyInterface string `json:"proxyInterface,omitempty" jsonschema:"Keenetic Proxy0/Proxy1… interface, when NDMS proxy mode is on"`
	SNI            string `json:"sni,omitempty"`
	// Running means the sing-box process is alive AND this proxy is
	// actually up (its TUN exists, or Clash reports the outbound). A
	// configured proxy that is down is listed with running=false rather
	// than omitted.
	Running bool `json:"running"`
}

// SingboxRule is one routing rule of the sing-box router. Index is the
// identity: sing-box evaluates rules in order and takes the first match,
// so position is what every edit addresses and what decides the outcome.
// Match is a rendered summary rather than the raw matcher fields — a
// model choosing "the YouTube rule" needs to read it, not reconstruct it.
type SingboxRule struct {
	Index    int    `json:"index"`
	Match    string `json:"match" jsonschema:"what the rule matches, in words"`
	Action   string `json:"action,omitempty" jsonschema:"route when empty"`
	Outbound string `json:"outbound,omitempty" jsonschema:"where matching traffic is sent"`
	// Managed marks rules generated by awg-manager. They are rewritten on
	// the next reconcile, so an edit to one does not survive.
	Managed bool `json:"managed" jsonschema:"true means awg-manager owns this rule and will rewrite it — do not edit it"`
}

// SingboxOutbound is a composite routing target a rule can point at.
type SingboxOutbound struct {
	Tag  string `json:"tag"`
	Type string `json:"type" jsonschema:"selector|urltest"`
	// Source says where the group came from (user, subscription, preset).
	Source string `json:"source,omitempty"`
}

// SingboxStaging describes the router's pending draft. The draft is
// shared with the web interface, which is why the caller is told when it
// was made rather than just that it exists.
type SingboxStaging struct {
	HasDraft  bool   `json:"hasDraft"`
	DraftedAt string `json:"draftedAt,omitempty"`
	// ValidationError is set when the draft would be rejected on apply.
	ValidationError string `json:"validationError,omitempty" jsonschema:"non-empty means applying this draft would fail"`
}

// SingboxDelay is one latency probe. Reachable exists because the delay
// test answers 0 both for "did not respond" and for a real zero, and 0 ms
// reads as an excellent result.
type SingboxDelay struct {
	Tag       string `json:"tag"`
	Reachable bool   `json:"reachable" jsonschema:"false means the proxy did not answer in time; delayMs carries no information then. Meaningless when busy is true"`
	DelayMs   int    `json:"delayMs" jsonschema:"round-trip in milliseconds, meaningless when reachable is false"`
	// Busy means a probe for this proxy was already running (the periodic
	// sweep shares the prober) and nothing was measured by this call. It
	// is neither reachable nor unreachable: retry in a few seconds.
	Busy bool `json:"busy" jsonschema:"true means no probe ran because one was already in progress — retry in a few seconds; reachable carries no information then"`
}

type SystemStatus struct {
	Version     string         `json:"version"`
	InstanceID  string         `json:"instanceId"`
	BootPhase   string         `json:"bootPhase"`
	AnyWANUp    bool           `json:"anyWANUp"`
	WAN         []WANInterface `json:"wan"`
	Singbox     SingboxStatus  `json:"singbox"`
	AuthEnabled bool           `json:"authEnabled"`
	RouterIP    string         `json:"routerIp,omitempty"`
	// Info is the raw /system/info payload (model, firmware, memory, kernel module…).
	Info map[string]any `json:"info,omitempty"`
}

type TunnelSummary struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Backend       string `json:"backend"`
	Enabled       bool   `json:"enabled"`
	State         string `json:"state"` // unknown|not_created|stopped|starting|running|…
	DefaultRoute  bool   `json:"defaultRoute"`
	InterfaceName string `json:"interfaceName,omitempty"`
	Endpoint      string `json:"endpoint,omitempty"`
	HasHandshake  bool   `json:"hasHandshake"`
}

type TrafficStats struct {
	Points    int     `json:"points"`
	PeakRate  float64 `json:"peakRate"`
	AvgRx     float64 `json:"avgRx"`
	AvgTx     float64 `json:"avgTx"`
	CurrentRx float64 `json:"currentRx"`
	CurrentTx float64 `json:"currentTx"`
	VolumeRx  int64   `json:"volumeRx"`
	VolumeTx  int64   `json:"volumeTx"`
}

type TunnelDetail struct {
	TunnelSummary
	ISPInterface string       `json:"ispInterface,omitempty"`
	AllowedIPs   []string     `json:"allowedIPs,omitempty"`
	Address      string       `json:"address,omitempty"`
	ProcessPID   int          `json:"processPID,omitempty"`
	Traffic1h    TrafficStats `json:"traffic1h"`
}

// TunnelAction values accepted by ControlTunnel.
const (
	ActionStart             = "start"
	ActionStop              = "stop"
	ActionRestart           = "restart"
	ActionEnable            = "enable"
	ActionDisable           = "disable"
	ActionSetDefaultRoute   = "set_default_route"
	ActionUnsetDefaultRoute = "unset_default_route"
)

type RouteTarget struct {
	Interface string `json:"interface,omitempty"`
	TunnelID  string `json:"tunnelId,omitempty"`
	Fallback  string `json:"fallback,omitempty"`
}

// MaxDomainsInOutput caps DNSRoute.Domains. A subscription-backed list
// expands to tens of thousands of domains; shipping them all into a model
// context on every list_dns_routes call is useless to the model and costs
// the router several copies of the list per call. ManualDomains — the
// user's own entries, and what add_dns_route needs to recreate a list —
// is never capped.
const MaxDomainsInOutput = 50

type DNSRoute struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Enabled bool   `json:"enabled"`
	// Domains is the expanded list (manual + subscriptions), truncated to
	// MaxDomainsInOutput entries; DomainCount is the real size.
	Domains       []string      `json:"domains" jsonschema:"expanded domains, at most the first 50; see domainCount for the full size"`
	DomainCount   int           `json:"domainCount"`
	ManualDomains []string      `json:"manualDomains,omitempty"`
	Subnets       []string      `json:"subnets,omitempty"`
	Routes        []RouteTarget `json:"routes"`
	Backend       string        `json:"backend,omitempty"`
}

// MaxDomainsInDetail caps one page of DNSRouteDetail.Domains. It is far
// larger than MaxDomainsInOutput because get_dns_route is asked for one
// list at a time and deliberately, but a subscription list still holds
// tens of thousands of domains — hence a page rather than the lot.
const MaxDomainsInDetail = 200

// DNSSubscription is a remote domain list feeding a routing list. Only
// the fields that explain where the domains came from are carried over.
type DNSSubscription struct {
	URL         string `json:"url"`
	Name        string `json:"name,omitempty"`
	LastFetched string `json:"lastFetched,omitempty"`
	LastCount   int    `json:"lastCount,omitempty"`
	LastError   string `json:"lastError,omitempty" jsonschema:"non-empty when the last fetch failed — the list may be stale"`
}

// DNSRouteDetail is one domain list in full: Domains is NOT capped, and
// the fields list_dns_routes drops (excludes, subscriptions) are present.
// Everything the web editor keeps purely for round-tripping — raw editor
// texts, dedupe reports, icon — still stays behind.
type DNSRouteDetail struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Enabled bool   `json:"enabled"`
	// Domains is the fully expanded list (manual entries plus everything
	// the subscriptions resolved to). get_dns_route pages it.
	Domains        []string          `json:"domains"`
	ManualDomains  []string          `json:"manualDomains,omitempty" jsonschema:"the user's own entries, before subscriptions are expanded"`
	Subnets        []string          `json:"subnets,omitempty"`
	Excludes       []string          `json:"excludes,omitempty" jsonschema:"domains carved out of this list"`
	ExcludeSubnets []string          `json:"excludeSubnets,omitempty"`
	Subscriptions  []DNSSubscription `json:"subscriptions,omitempty"`
	Routes         []RouteTarget     `json:"routes"`
	Backend        string            `json:"backend,omitempty"`
	CreatedAt      string            `json:"createdAt,omitempty"`
	UpdatedAt      string            `json:"updatedAt,omitempty"`
}

// Summary projects the full record onto the capped list form, so
// list_dns_routes and get_dns_route cannot drift apart in what they mean
// by a field. Domains is truncated with a full three-index slice: the
// result must not be able to grow into the detail's backing array.
func (d DNSRouteDetail) Summary() DNSRoute {
	out := DNSRoute{
		ID: d.ID, Name: d.Name, Enabled: d.Enabled,
		Domains: d.Domains, DomainCount: len(d.Domains),
		ManualDomains: d.ManualDomains, Subnets: d.Subnets,
		Backend: d.Backend,
		Routes:  append([]RouteTarget(nil), d.Routes...),
	}
	if len(out.Domains) > MaxDomainsInOutput {
		out.Domains = out.Domains[:MaxDomainsInOutput:MaxDomainsInOutput]
	}
	if out.Domains == nil {
		out.Domains = []string{}
	}
	if out.Routes == nil {
		out.Routes = []RouteTarget{}
	}
	return out
}

// DNSRouteInput has no `enabled` field on purpose: dnsroute.Create always
// creates the list enabled and pushes the routing into NDMS immediately, so
// honouring enabled:false would mean going live and then tearing it down a
// moment later — and leaving the list ENABLED if that second call failed.
// A list created through MCP is always enabled; disable it from the web UI.
type DNSRouteInput struct {
	Name     string   `json:"name" jsonschema:"human-readable list name"`
	Domains  []string `json:"domains" jsonschema:"domains to route (suffix match), e.g. [\"youtube.com\"]; geosite:/geoip: tags and CIDR subnets are also accepted"`
	TunnelID string   `json:"tunnelId" jsonschema:"target tunnel id from list_tunnels"`
}

// DNSRouteUpdate is a partial edit of one list: an omitted field is left
// alone. There is deliberately no way to clear a field — dnsroute.Update
// itself treats a zero value as "not sent", and inventing a clear here
// would mean a payload that empties Name or the domains on any caller who
// simply forgot a field. Deleting is remove_dns_route's job.
//
// The entries field is named manualDomains, not domains, on purpose: the
// `domains` of get_dns_route is the EXPANDED list (subscriptions included),
// and a model that read it and handed it back under the same name would
// turn every subscription domain into a manual copy.
type DNSRouteUpdate struct {
	RouteID       string   `json:"routeId" jsonschema:"list id from list_dns_routes"`
	Name          string   `json:"name,omitempty" jsonschema:"new list name; omit to keep the current one"`
	ManualDomains []string `json:"manualDomains,omitempty" jsonschema:"replaces ALL of the list's own entries — domains and CIDR subnets alike — so read the current ones from get_dns_route's manualDomains (NOT domains, which includes subscription entries) and pass back everything you want to keep; omit to leave them untouched"`
	TunnelID      string   `json:"tunnelId,omitempty" jsonschema:"send the list through this tunnel instead; omit to keep the current target"`
}

type StaticRoute struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	TunnelID string   `json:"tunnelID"`
	Subnets  []string `json:"subnets"`
	Fallback string   `json:"fallback,omitempty"`
	Enabled  bool     `json:"enabled"`
}

type StaticRouteInput struct {
	Name     string   `json:"name"`
	TunnelID string   `json:"tunnelId" jsonschema:"target tunnel id from list_tunnels"`
	Subnets  []string `json:"subnets" jsonschema:"CIDR list, e.g. [\"10.0.0.0/8\"]"`
	Enabled  *bool    `json:"enabled,omitempty" jsonschema:"default true"`
}

type ClientRoute struct {
	ID             string `json:"id"`
	ClientIP       string `json:"clientIp"`
	ClientHostname string `json:"clientHostname,omitempty"`
	TunnelID       string `json:"tunnelId"`
	Fallback       string `json:"fallback"`
	Enabled        bool   `json:"enabled"`
}

type ClientRouteInput struct {
	ClientIP string `json:"clientIp" jsonschema:"LAN client IPv4 from list_devices"`
	TunnelID string `json:"tunnelId" jsonschema:"tunnel id, or empty string to remove the route"`
	Fallback string `json:"fallback,omitempty" jsonschema:"drop|bypass when the tunnel is down; default bypass"`
}

type AccessPolicy struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Interfaces  []string `json:"interfaces"`
	DeviceCount int      `json:"deviceCount"`
	IsStandard  bool     `json:"isStandard"`
}

type Device struct {
	MAC      string `json:"mac"`
	IP       string `json:"ip"`
	Name     string `json:"name"`
	Hostname string `json:"hostname"`
	Active   bool   `json:"active"`
	Policy   string `json:"policy"`
}

type LogsQuery struct {
	Bucket   string   `json:"bucket,omitempty" jsonschema:"app|singbox, default app"`
	Groups   []string `json:"groups,omitempty" jsonschema:"e.g. tunnel, routing, system, singbox"`
	Level    string   `json:"level,omitempty" jsonschema:"minimum level: debug|info|warn|error"`
	Lines    int      `json:"lines,omitempty" jsonschema:"1..500, default 100"`
	Contains string   `json:"contains,omitempty" jsonschema:"case-insensitive substring filter on message"`
	Raw      bool     `json:"raw,omitempty" jsonschema:"true returns IPs and domains unmasked; by default they are partially redacted, as in the web UI"`
}

type LogEntry struct {
	Timestamp string `json:"timestamp"`
	Level     string `json:"level"`
	Group     string `json:"group"`
	Subgroup  string `json:"subgroup"`
	Action    string `json:"action,omitempty"`
	Target    string `json:"target,omitempty"`
	Message   string `json:"message"`
	// Repeats > 1 means the buffer collapsed identical consecutive lines
	// into this one; LastSeen is when the latest of them arrived.
	Repeats  int    `json:"repeats,omitempty"`
	LastSeen string `json:"lastSeen,omitempty"`
}

type ConnectivityResult struct {
	TunnelID  string `json:"tunnelId"`
	Connected bool   `json:"connected"`
	LatencyMs *int   `json:"latencyMs,omitempty"`
	Reason    string `json:"reason,omitempty"`
	HTTPCode  *int   `json:"httpCode,omitempty"`
}

// IPCheckResult compares the external IP seen through a tunnel with the
// one seen straight over the WAN. IPChanged is the answer to the question
// users actually ask — "is my traffic really going through the VPN" —
// which a reachability probe cannot give.
type IPCheckResult struct {
	TunnelID string `json:"tunnelId"`
	// DirectIP is the address the router shows over the WAN, bypassing the
	// tunnel. Empty when that leg of the check failed.
	DirectIP string `json:"directIp,omitempty"`
	// VpnIP is the address seen through the tunnel.
	VpnIP      string `json:"vpnIp,omitempty"`
	EndpointIP string `json:"endpointIp,omitempty" jsonschema:"the tunnel peer's address, for telling apart two tunnels landing in the same country"`
	IPChanged  bool   `json:"ipChanged" jsonschema:"true means the tunnel really carries the traffic; FALSE means the external IP is the same with and without it — the traffic is NOT going through the tunnel"`
}

type MonitoringCell struct {
	TargetID  string    `json:"targetId"`
	TunnelID  string    `json:"tunnelId"`
	OK        bool      `json:"ok"`
	LatencyMs *int      `json:"latencyMs"`
	TS        time.Time `json:"ts"`
}

type MonitoringTarget struct {
	ID   string `json:"id"`
	Host string `json:"host"`
	Name string `json:"name"`
}

type MonitoringTunnel struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type MonitoringMatrix struct {
	Targets   []MonitoringTarget `json:"targets"`
	Tunnels   []MonitoringTunnel `json:"tunnels"`
	Cells     []MonitoringCell   `json:"cells"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// Connection is one open flow, trimmed to what identifies it: who, where
// and through which tunnel. Byte counters and conntrack internals are
// left out — an agent answering "what is this device doing" needs the
// destination, not the TTL.
type Connection struct {
	Protocol   string `json:"protocol"`
	Src        string `json:"src"`
	SrcPort    int    `json:"srcPort,omitempty"`
	Dst        string `json:"dst"`
	DstPort    int    `json:"dstPort,omitempty"`
	State      string `json:"state,omitempty"`
	Interface  string `json:"interface,omitempty"`
	TunnelID   string `json:"tunnelId,omitempty" jsonschema:"empty means the flow does not go through a tunnel"`
	TunnelName string `json:"tunnelName,omitempty"`
	ClientName string `json:"clientName,omitempty" jsonschema:"LAN device the flow came from, when known"`
}

// ConnectionsQuery filters the flow table. Limit is already clamped by
// the tool.
type ConnectionsQuery struct {
	TunnelID string
	ClientIP string
	Limit    int
}

// PingCheckLogEntry is one automatic health check of one tunnel.
type PingCheckLogEntry struct {
	Timestamp  string `json:"timestamp"`
	TunnelID   string `json:"tunnelId"`
	TunnelName string `json:"tunnelName,omitempty"`
	Success    bool   `json:"success"`
	LatencyMs  int    `json:"latencyMs,omitempty" jsonschema:"meaningless when success is false"`
	Error      string `json:"error,omitempty"`
	// StateChange marks the entries that matter most: the moment a tunnel
	// was switched off after repeated failures, or came back.
	StateChange string `json:"stateChange,omitempty" jsonschema:"link_toggle or recovered on the checks that changed the tunnel's state"`
}

// DiagnosticsRun is the answer to starting a sweep. Started is false when
// one was already running — the call is not an error, but the caller must
// not report a fresh run either.
type DiagnosticsRun struct {
	Started bool   `json:"started" jsonschema:"false when a sweep was already in progress"`
	Status  string `json:"status" jsonschema:"running|done|error|idle"`
	Message string `json:"message,omitempty"`
}

// DiagnosticsProblem is one check that did not pass.
type DiagnosticsProblem struct {
	Name       string `json:"name"`
	Status     string `json:"status" jsonschema:"fail|warn|error"`
	Detail     string `json:"detail"`
	TunnelID   string `json:"tunnelId,omitempty"`
	TunnelName string `json:"tunnelName,omitempty"`
}

// DiagnosticsResult is the sweep's outcome. The counts describe every
// check; Problems lists only the ones that did not pass, worst first, so
// a short list never means a clean run on its own.
type DiagnosticsResult struct {
	Status      string               `json:"status" jsonschema:"done when the report is complete; running means these numbers are from an EARLIER sweep"`
	GeneratedAt string               `json:"generatedAt,omitempty"`
	Passed      int                  `json:"passed"`
	Failed      int                  `json:"failed"`
	Warnings    int                  `json:"warnings"`
	Skipped     int                  `json:"skipped"`
	Problems    []DiagnosticsProblem `json:"problems" jsonschema:"checks that did not pass, failures before warnings"`
}

// ManagedServer is a WireGuard server hosted on this router. Two kinds
// appear in one list: servers awg-manager created and fully manages, and
// built-in or marked NDMS servers it only observes. Only the first kind
// accepts the peer tools, hence Managed — the two id spaces were once
// presented as one, and no peer tool could be completed end to end.
type ManagedServer struct {
	ID            string `json:"id"`
	InterfaceName string `json:"interfaceName"`
	Description   string `json:"description"`
	Status        string `json:"status,omitempty" jsonschema:"up|down; empty for servers awg-manager manages itself"`
	Connected     bool   `json:"connected"`
	ListenPort    int    `json:"listenPort"`
	PeerCount     int    `json:"peerCount"`
	// Managed is true for servers created by awg-manager. The peer tools
	// (list_server_peers, add_server_peer, …) work only on these.
	Managed bool `json:"managed" jsonschema:"true means the peer tools accept this server's id"`
}

// ServerPeer is one client of a WireGuard server hosted on this router.
// The peer's private key and preshared key are NOT here: they exist in
// storage only to render the client's .conf, which get_server_peer_config
// returns on an explicit call.
type ServerPeer struct {
	PublicKey   string `json:"publicKey" jsonschema:"identifies the peer for the other peer tools"`
	Description string `json:"description" jsonschema:"whose device this is"`
	TunnelIP    string `json:"tunnelIp" jsonschema:"the peer's address inside the tunnel, e.g. 10.0.0.2/32"`
	DNS         string `json:"dns,omitempty"`
	Enabled     bool   `json:"enabled" jsonschema:"a disabled peer keeps its keys and address but cannot connect"`
}

// AddPeerInput creates a client on a hosted server. TunnelIP is optional:
// left empty, the daemon allocates the first free address in the server's
// subnet. Asking the model to invent one produces either a collision or a
// peer outside the subnet, which simply never connects.
type AddPeerInput struct {
	ServerID    string `json:"serverId" jsonschema:"id of a server with managed=true in list_managed_servers"`
	Description string `json:"description" jsonschema:"whose device this is, e.g. \"phone\" — required, it is how the peer is recognised later"`
	TunnelIP    string `json:"tunnelIp,omitempty" jsonschema:"optional address inside the tunnel (10.0.0.5/32); omit to let the router pick the first free one"`
	DNS         string `json:"dns,omitempty" jsonschema:"optional DNS server for the client config"`
}

// PingCheckRun is what run_pingcheck returns. The sweep itself runs in
// the background — on a router with several tunnels and a 5 s probe
// timeout a synchronous sweep would hold the call for half a minute with
// no way to cancel it — so Tunnels is the status as of the LAST completed
// check, and Triggered says whether this call started a new one (false
// when one was already in flight).
type PingCheckRun struct {
	Triggered bool              `json:"triggered" jsonschema:"true if this call started a new check; false if monitoring is disabled, a check is already running, or one started less than ~10 s ago"`
	Tunnels   []PingCheckStatus `json:"tunnels" jsonschema:"status as of the last COMPLETED check — call again in ~10 s for the result of the one just triggered"`
}

type PingCheckStatus struct {
	TunnelID    string `json:"tunnelId"`
	TunnelName  string `json:"tunnelName"`
	Enabled     bool   `json:"enabled"`
	Status      string `json:"status"`
	Method      string `json:"method"`
	LastLatency int    `json:"lastLatency"`
}
