package vlink

import "testing"

const ttTOMLExport = "\xEF\xBB\xBF# generated by endpoint\nhostname = \"vpn.example.com\"\naddresses = [\"1.2.3.4:443\", \"5.6.7.8:8443\"]\ncustom_sni = \"\"\nhas_ipv6 = true\nusername = \"premium\"\npassword = \"s3cretPass\"\nclient_random_prefix = \"aabb\"\nskip_verification = false\ncertificate = \"\"\nupstream_protocol = \"http3\"\nanti_dpi = true\nname = \"Export\"\ndns_upstreams = []\n"

const ttTOMLClient = "loglevel = \"info\"\nvpn_mode = \"general\"\nkillswitch_enabled = true\n[endpoint]\nhostname = \"vpn.example.com\"\naddresses = [\"1.2.3.4:443\"]\nusername = \"premium\"\npassword = \"s3cretPass\"\nclient_random = \"aabb\"\nskip_verification = true\nupstream_protocol = \"http2\"\nanti_dpi = false\n[listener.socks]\naddress = \"127.0.0.1:1080\"\n"

func TestIsTrustTunnelTOML(t *testing.T) {
	yes := []string{ttTOMLExport, ttTOMLClient}
	no := []string{"", "{\"profiles\":[]}", "proxies:\n  - name: x\n", "vless://x@h:1#a\n", "hostname = \"h\"\n" /* без адресов/кредов */, "[endpoint]\nhostname = \"h\"\n", "[", "[{\"a\":1}]"}
	for _, b := range yes {
		if !IsTrustTunnelTOML([]byte(b)) {
			t.Fatalf("must detect: %q", b[:20])
		}
	}
	for _, b := range no {
		if IsTrustTunnelTOML([]byte(b)) {
			t.Fatalf("must not detect: %q", b)
		}
	}
}

func TestParseTrustTunnelTOML_ExportFormat(t *testing.T) {
	res := ParseTrustTunnelTOML([]byte(ttTOMLExport))
	if len(res.Errors) != 0 || len(res.Outbounds) != 2 {
		t.Fatalf("res: %+v", res)
	}
	if res.Outbounds[0].Tag != "Export-1" || !res.Outbounds[0].MultiAddress {
		t.Fatalf("tag/multi: %+v", res.Outbounds[0])
	}
	tls := ttOutboundMap(t, res.Outbounds[0])["tls"].(map[string]any)
	if tls["fragment"] != true || tls["server_name"] != "vpn.example.com" {
		t.Fatalf("tls: %v", tls)
	}
}

func TestParseTrustTunnelTOML_ClientFormat(t *testing.T) {
	res := ParseTrustTunnelTOML([]byte(ttTOMLClient))
	if len(res.Errors) != 0 || len(res.Outbounds) != 1 {
		t.Fatalf("res: %+v", res)
	}
	p := res.Outbounds[0]
	if p.Tag != "vpn.example.com" || p.MultiAddress {
		t.Fatalf("meta: %+v", p)
	}
	tls := ttOutboundMap(t, p)["tls"].(map[string]any)
	if tls["insecure"] != true {
		t.Fatalf("tls: %v", tls)
	}
}

func TestParseTrustTunnelTOML_Garbage(t *testing.T) {
	res := ParseTrustTunnelTOML([]byte("hostname = \"h\"\naddresses = [\"noport\"]\nusername = \"u\"\npassword = \"p\"\n"))
	if len(res.Outbounds) != 0 || len(res.Errors) != 1 || res.Errors[0].LineIdx != 0 || res.Errors[0].Scheme != "trusttunnel-toml" {
		t.Fatalf("res: %+v", res)
	}
}
