// Code generated by scripts/build-singbox.sh; DO NOT EDIT.
package installer

const RequiredVersion = "1.14.0-alpha.23"

var EmbeddedBinaries = map[string]BinarySpec{
	"mipsel-3.4":   {Version: RequiredVersion, URL: "https://github.com/miuirussia/awg-manager/releases/download/latest/sing-box-1.14.0-alpha.23-mipsel-3.4", SHA256: "76e67bb07b5c2bf4cef108c2f21a5ffaa684d124c21ffe220fc89b39cf1de934"},
	"mips-3.4":     {Version: RequiredVersion, URL: "https://github.com/miuirussia/awg-manager/releases/download/latest/sing-box-1.14.0-alpha.23-mips-3.4", SHA256: "a7310b0c99b27d62da397d84be923b57afd4462de341ae7b570fde5650bd0ad3"},
	"aarch64-3.10": {Version: RequiredVersion, URL: "https://github.com/miuirussia/awg-manager/releases/download/latest/sing-box-1.14.0-alpha.23-aarch64-3.10", SHA256: "24db6000b6fbc48ba6c1bebd6693c10e5568c18447680a81e99a14437473cd00"},
}
