// Code generated by scripts/build-singbox-binaries.sh; DO NOT EDIT.
package installer

const RequiredVersion = "1.13.11"

var EmbeddedBinaries = map[string]BinarySpec{
	"mipsel-3.4":   {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/singbox/1.13.11/sing-box-1.13.11-mipsel-3.4.upx", SHA256: "b568ed512c97c1c03a44394f63f25d40a0a31ba07928c6dc5c8c92a609ec92ed"},
	"mips-3.4":     {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/singbox/1.13.11/sing-box-1.13.11-mips-3.4.upx", SHA256: "9e1b0cc1da0e63763716d1e6195496a2779c25eaeea4d4d14f1ce7afaefa7c74"},
	"aarch64-3.10": {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/singbox/1.13.11/sing-box-1.13.11-aarch64-3.10.upx", SHA256: "76278cb44ca967403f8af00787f9771afed2f40f684496727a829ee7566e3109"},
}
